// Automatically generated by astro-icon
// 1bec281facabe356db31424e376e6eae93d12fdae8fcce4aa029295c452c3633

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-left"
		| "icon-close"
		| "logo";
}