version: "3.8"
services:
  front:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend

  api:
    build: ./backend
    depends_on:
      - redis
    ports:
      - "3001:3001"
    networks: 
     - network-backend
  
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data/db
    environment:
      REDIS_ROOT_USERNAME: username
      REDIS_ROOT_PASSWORD: password
    networks:
     - network-backend
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - front
    volumes:
      - /etc/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
    environment:
      - VIRTUAL_HOST=test.127.0.0.1.nip.io
    restart: always

networks:
  network-backend:

volumes:
  redis_data:
